version: "3.5"

services:
  angular-seed:
    build:
      context: ./.docker
      target: angular-seed-${SEED_TYPE}
      args:
        PROJECT_NAME: ${PROJECT_NAME}
        PROJECT_FOLDER: ${PROJECT_FOLDER}
        SEED_TYPE: ${SEED_TYPE}
    image: ${PROJECT_FOLDER}/angular-seed-${SEED_TYPE}
    container_name: ${PROJECT_FOLDER}
